# Generated by Django 5.2.9 on 2025-12-05 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sereneapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepressionPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sadness", models.CharField(max_length=20)),
                ("euphoric", models.CharField(max_length=20)),
                ("exhausted", models.CharField(max_length=20)),
                ("sleep_disorder", models.CharField(max_length=20)),
                ("mood_swing", models.CharField(max_length=20)),
                ("suicidal_thoughts", models.CharField(max_length=20)),
                ("anorexia", models.CharField(max_length=20)),
                ("authority_respect", models.CharField(max_length=20)),
                ("try_explanation", models.CharField(max_length=20)),
                ("aggressive_response", models.CharField(max_length=20)),
                ("ignore_move_on", models.CharField(max_length=20)),
                ("nervous_breakdown", models.CharField(max_length=20)),
                ("admit_mistakes", models.CharField(max_length=20)),
                ("overthinking", models.CharField(max_length=20)),
                (
                    "prediction_result",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sereneapp.register",
                    ),
                ),
            ],
        ),
    ]
