# Generated by Django 5.2.9 on 2025-12-08 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sereneapp", "0002_depressionprediction"),
    ]

    operations = [
        migrations.CreateModel(
            name="ADHDPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                ("sleep_hour_avg", models.FloatField()),
                ("easily_distracted", models.IntegerField()),
                ("forgetful_daily_tasks", models.IntegerField()),
                ("poor_organization", models.IntegerField()),
                ("difficulty_sustaining_attention", models.IntegerField()),
                ("restlessness", models.IntegerField()),
                ("impulsivity_score", models.IntegerField()),
                ("screen_time_daily", models.FloatField()),
                ("phone_unlocks_per_day", models.IntegerField()),
                ("working_memory_score", models.IntegerField()),
                ("symptom_score", models.IntegerField()),
                ("adhd_result", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sereneapp.register",
                    ),
                ),
            ],
        ),
    ]
