# Generated by Django 5.2.9 on 2025-12-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sereneapp", "0003_adhdprediction"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="gender",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="register",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="register",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="phone",
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="register",
            name="place",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="register",
            name="role",
            field=models.CharField(default="user", max_length=20),
        ),
    ]
