# Generated by Django 5.2.9 on 2025-12-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sereneapp", "0004_register_gender_alter_register_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_hospital_doctor_register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                (
                    "qualification",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("experience", models.IntegerField(blank=True, null=True)),
                (
                    "hospital_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("hospital_address", models.TextField(blank=True, null=True)),
                (
                    "hospital_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("role", models.CharField(default="hospital_doctor", max_length=30)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("place", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="hospital_doctor_images/"
                    ),
                ),
                (
                    "medical_id",
                    models.ImageField(
                        blank=True, null=True, upload_to="hospital_medical_ids/"
                    ),
                ),
                ("available", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
