# Generated by Django 5.2.9 on 2025-12-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sereneapp", "0005_tbl_hospital_doctor_register"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="register",
            name="gender",
        ),
        migrations.AlterField(
            model_name="register",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="register",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=11, null=True
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=11, null=True
            ),
        ),
        migrations.AlterField(
            model_name="register",
            name="phone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="register",
            name="place",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="register",
            name="role",
            field=models.CharField(default="user", max_length=50),
        ),
    ]
