# Generated by Django 5.2.9 on 2025-12-13 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sereneapp", "0006_remove_register_gender_alter_register_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HospitalDoctorFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_feedbacks",
                        to="sereneapp.tbl_hospital_doctor_register",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_feedbacks",
                        to="sereneapp.register",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HospitalDoctorTimeSlotGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("timeslots", models.JSONField(blank=True, default=list)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_groups",
                        to="sereneapp.tbl_hospital_doctor_register",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HospitalBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.CharField(max_length=20)),
                ("status", models.CharField(default="booked", max_length=20)),
                ("is_booked", models.BooleanField(default=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sereneapp.tbl_hospital_doctor_register",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sereneapp.register",
                    ),
                ),
                (
                    "timeslot_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sereneapp.hospitaldoctortimeslotgroup",
                    ),
                ),
            ],
        ),
    ]
